### ISSUE TITLE
README not up to date

### ISSUE THREAD

**Issue by ghost** [TecArt/tecart-http-proxy#6]
There's a lot of problems with the current README and it needs to be updated:

- [x] Ubuntu needs multiverse repos
- [x] Python 3 deprecated the venv command
- [x] Installation for systemd is more likely nowadays and supervisor isn't needed anymore

**Comment by irLinja** [comment]
let me take this @maik-kulbe

**Comment by ghost** [comment]
Merged your changes. Thanks a lot for your contribution!

**Comment by irLinja** [comment]
your welcome :smile:
